### ISSUE TITLE
パソコンのメモリが足りない！

### ISSUE THREAD

**Issue by Kei19950532** [Kei19950532/soukyoku-log#1]
## 現象の詳細

メモリが足りなくてWSLを動かすとPCがバグります。

## 再現方法

予測不能。

## デバイス

Windows PC ホーム

## ブラウザ

GoogleChrome

## OS(できる限りバージョンも記載)

Windows10

## 追加のコメント

メモリ買いますごめんなさい。

**Comment by niakachan** [comment]
マザーボードの型番を教えてくれればこっちで探します(*^^*)

**Comment by Kei19950532** [comment]
System Manufacturer: Thirdwave Diginnos Co., Ltd.
System Model: ZV

だと思います！
よろしくお願いします。

**Comment by niakachan** [comment]
このへんでいきますよ～
https://kakaku.com/item/K0001171746/

**Comment by Kei19950532** [comment]
了解しました。
助かります。

**Comment by Kei19950532** [comment]
教えて頂いたメモリを搭載した結果、問題なく動作しました。
ありがとうございました。

（これはissueのテストと実際のやり取りを兼ねた投稿です）
