### ISSUE TITLE
ユーザーが数値を記録する毎にランダムで様々なメッセージを表示させたい。

### ISSUE THREAD

**Issue by Kei19950532** [Kei19950532/soukyoku-log#3]
## この機能はどういった問題に関連しているか

どんなアプリでも抱える問題だが、ただ数値を入力して記録していくだけではすぐに飽きられる。

実用性も大事だが、ユーザーが使っていて楽しいと思えるものを作りたいと考えたときに普段自分でもよく使っているマインドフルネスアプリは記録を残すと応援メッセージを送ってくれたり「何日連続で記録中」等と教えてくれる為、継続しやすいと感じた事を思い出した。

それによって長くアプリを使用してもらえるという事に繋がると考えた。
よって、実装したい。

## 希望する機能の内容

上記の通り。

## 検討した代替案

特になし。

## 追加コメント

特になし。

**Comment by niakachan** [comment]
まずこれを見て思ったことを書きます。

- メッセージパターンをどのように定義するかを先に決めたい
- 応援メッセージパターンは後から追加できたほうがいいけどどれくらいバリエーションが作れるか
- 気をつけないと訴えられそう（言葉選びが大切そう）

なのである程度のセーフラインの基準は必要かなと思います。

**Comment by Kei19950532** [comment]
なるほど、意見ありがとうございます。

パターン定義に関しては私の中では大きく分けて２つあり、「継続的に記録している場合は労いやお褒めの言葉」「数日おきの記録の場合は毎日記録をするように促す言葉」にしたいと考えています。
よくあるこの手のアプリでは通知を使って促したりする事もあるでしょうが、今回はそこまで複雑にはしないでシンプルにしたいなと。

実際にリリースするサービスではないので、メッセージバリエーションはまずは3個程でも良いかなと考えています。
但し、あとから追加できるように…というのは同意します。

言葉選びは確かに慎重に選ぶ必要がありますね。
「お疲れ様です」「おめでとうございます」「頑張りましょう」等の誰が言われても悪気を感じないようなシンプルなものにするのはどうでしょうか。

ともあれ、セーフラインの基準はしっかりと決めておく事にします。

**Comment by Kei19950532** [comment]
間違えてCloseしたため、再度Openします。
