### ISSUE TITLE
記録されているデータを外部に共有する機能を実装したい。

### ISSUE THREAD

**Issue by Kei19950532** [Kei19950532/soukyoku-log#4]
## この機能はどういった問題に関連しているか

実体験として、双極性障害は客観的に診察が難しい。
その問題に対し、もしも医療機関や第三者に対して自身の体調のデータを送る事が出来たなら状態把握が今よりも容易になるのではないかと考えた。

現状でもQRコードを読み込む事で電子お薬手帳にデータを移動させたり、バーコードを認識する事でデータのやり取りを簡易化させてる機能は存在する。

技術的には難しいかもしれないが、あったら便利だと思うので実装したい。

## 希望する機能の内容

アプリ内に記録されたデータのQRコード化、または何かしらにテキスト化（PDF系）して第三者に共有できるようになる機能。

## 検討した代替案

検討・検索中。

## 追加コメント

特になし。

**Comment by niakachan** [comment]
良いと思います。
QRコードでURLを発行し、そこにアクセスすることでPDFなどをダウンロード…。
ただ、重大な個人情報が含まれるというのが問題です。

なので下記提案をします。

1. アプリの登録者同士で、かつフレンド登録をしていないとデータは送れない
2. 傍受されたり配布される危険性が高い生のPDFデータは避ける
3. 特定フレンドへの公開フラグを立てればQRコードなしでもいつでも見てもらえる
4. フラグは本人の判断でいつでも取り消せる。

そういう感じでどうでしょうか？

**Comment by Kei19950532** [comment]
確かに個人情報の漏洩は一番避けるべき部分ですね。

その４つの提案に同意します。
それに加えて私の方からひとつ提案宜しいでしょうか？

どの程度の･･･という細かな部分までは突き詰められていませんが、ユーザーが自分自身でどこまでの情報を第三者に共有するかを設定できるようにする･･･という機能も追加するというのはどうでしょうか。

何かご意見在りましたらよろしくお願いします。

**Comment by niakachan** [comment]
>細かな部分までは突き詰められていませんが、ユーザーが自分自身でどこまでの情報を第三者に共有するかを設定できるようにする･･･という機能も追加するというのはどうでしょうか。

良いと思います。
これはユーザーモデルの設計にも関わってくることなので、どういう情報を保持するかは早めに決めてしまいたいですね

**Comment by Kei19950532** [comment]
了解しました。
では新たなissueを開き、またそこで議論をしていきたいと思います。
