### ISSUE TITLE
ログインした会員同士が交流できるSNS的な機能を実装したい。

### ISSUE THREAD

**Issue by Kei19950532** [Kei19950532/soukyoku-log#6]
## この機能はどういった問題に関連しているか

実体験として、この手の疾患とうまく付き合う為には「相談相手」と「正しい服薬」が必要である。
前者に関してはアプリ内に似たような悩みを持つ人たち同士が集まれるSNS的な場所があれば、それらは解決できると考えた。

なお、既存のTwitterやFacebookのような大手SNSへの投稿機能は実装しないものとしたい。

## 希望する機能の内容

システムとしてはTwitterクローンを制作したいと考えているが、デザインや仕様は若干変更したい。
タグはユーザーが増やすのではなく、こちらが予め用意したものを活用してもらう…など。

## 検討した代替案

特になし。

## 追加コメント

自身の疾患を公衆に晒したくはないと考える人も多い為、あえてTwitter・Facebookのような大手SNSへの投稿機能は使えないようにしたい。
ただし、電子化してデータを送るという機能自体は実装したいので、ここの部分と混合しないようにしたい。

他、追加のご意見があればお願いします。

**Comment by niakachan** [comment]
Twitterクローンを作って万が一アクセスが増えすぎるとインフラの設計が大変そうです。（私の経験上、AWSやGCPでコンテナデプロイをすることで済ませても従量課金制は思った以上にお金がかかります）

なのでまずは投稿機能は後回しにして、フォロー、フォロワー機能くらいにしておくと良いかもしれません。
デリケートな問題を扱うアプリなので、どこまでの距離感が最適解になるか、よく吟味しましょう。

プロフィールの設定くらいはできるようにしていいかも？

**Comment by Kei19950532** [comment]
おっしゃる通りです、申し訳ありません。
インフラ関係の負担の計算を失念しておりました。

了解しました、では最初はフォロー・フォロワー機能とプロフィール設定の実装という事にしましょうか。

ユーザー間の距離感の問題は #3 でも似たような件があったように疾患を取り扱う以上は慎重に行きたいと思います。
